"""
LifeOS Backend — Email Service
Utility to send secure emails via SMTP (e.g., Gmail).
"""

import smtplib
import logging
from typing import List, Optional
from email.message import EmailMessage
from app.config import get_settings

logger = logging.getLogger("lifeos.email")


def send_verification_email(recipient_email: str, code: str) -> bool:
    """
    Sends a verification code email to the specified recipient.
    Returns True if successful, False otherwise.
    """
    settings = get_settings()
    
    if not settings.SMTP_EMAIL or not settings.SMTP_PASSWORD or settings.SMTP_PASSWORD == "PASTE_16_CHAR_APP_PASSWORD_HERE":
        logger.error("Email service is not configured! Check SMTP_EMAIL and SMTP_PASSWORD in .env")
        return False
        
    try:
        msg = EmailMessage()
        msg.set_content(
            f"Hello,\n\n"
            f"You requested to reset your password for LifeOS.\n\n"
            f"Your verification code is: {code}\n\n"
            f"This code will expire in 15 minutes.\n\n"
            f"If you did not request this, please ignore this email."
        )
        msg["Subject"] = "LifeOS - Your Password Reset Code"
        msg["From"] = f"LifeOS <{settings.SMTP_EMAIL}>"
        msg["To"] = recipient_email
        
        # Connect to Gmail SMTP server
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(settings.SMTP_EMAIL, settings.SMTP_PASSWORD)
            server.send_message(msg)
            
        logger.info(f"Verification email successfully sent to {recipient_email}")
        return True
        
    except Exception as e:
        logger.error(f"Failed to send email to {recipient_email}: {str(e)}")
        return False

def send_admin_reset_password_email(recipient_email: str, new_password: str) -> bool:
    """
    Sends an email with the new reset password generated by the admin.
    """
    settings = get_settings()
    
    if not settings.SMTP_EMAIL or not settings.SMTP_PASSWORD or settings.SMTP_PASSWORD == "PASTE_16_CHAR_APP_PASSWORD_HERE":
        logger.error("Email service is not configured! Check SMTP_EMAIL and SMTP_PASSWORD in .env")
        return False
        
    try:
        msg = EmailMessage()
        msg.set_content(
            f"Hello,\n\n"
            f"An administrator has reset your password for LifeOS.\n\n"
            f"Your new password is: {new_password}\n\n"
            f"Please log in and change your password immediately."
        )
        msg["Subject"] = "LifeOS - Administrator Password Reset"
        msg["From"] = f"LifeOS <{settings.SMTP_EMAIL}>"
        msg["To"] = recipient_email
        
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(settings.SMTP_EMAIL, settings.SMTP_PASSWORD)
            server.send_message(msg)
            
        logger.info(f"Admin reset password email successfully sent to {recipient_email}")
        return True
        
    except Exception as e:
        logger.error(f"Failed to send admin reset password email to {recipient_email}: {str(e)}")
        return False

def send_login_alert_email(recipient_email: str, ip_address: str, user_agent: str, time_str: str) -> bool:
    """
    Sends an email alerting the user of a new login to their account.
    """
    settings = get_settings()
    if not settings.SMTP_EMAIL or not settings.SMTP_PASSWORD or settings.SMTP_PASSWORD == "PASTE_16_CHAR_APP_PASSWORD_HERE":
        return False
        
    try:
        msg = EmailMessage()
        
        # Fallback Plain Text
        msg.set_content(
            f"Hello,\n\n"
            f"We noticed a new login to your LifeOS account.\n\n"
            f"Time: {time_str}\n"
            f"IP Address: {ip_address}\n"
            f"Device/Browser: {user_agent}\n\n"
            f"If this was you, you can safely ignore this email.\n"
            f"If you do not recognize this login, please change your password immediately."
        )
        
        # Aesthetic HTML Template
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <body style="margin: 0; padding: 0; background-color: #f8fafc; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;">
          <div style="max-width: 600px; margin: 40px auto; background-color: #ffffff; border-radius: 16px; overflow: hidden; box-shadow: 0 10px 25px rgba(0, 0, 0, 0.05); border: 1px solid #e2e8f0;">
            <div style="background: linear-gradient(135deg, #2563eb, #06b6d4); padding: 24px; text-align: center;">
              <h1 style="margin: 0; color: #ffffff; font-size: 24px; font-weight: 700;">New Login Alert</h1>
            </div>
            <div style="padding: 40px 32px;">
              <p style="font-size: 16px; color: #475569; margin-top: 0;">We noticed a new login to your LifeOS account.</p>
              
              <div style="background-color: #f1f5f9; padding: 20px; border-radius: 8px; margin: 24px 0;">
                <p style="margin: 0 0 12px 0; font-size: 14px; color: #64748b;"><strong>Time:</strong> {time_str}</p>
                <p style="margin: 0 0 12px 0; font-size: 14px; color: #64748b;"><strong>IP Address:</strong> {ip_address}</p>
                <p style="margin: 0; font-size: 14px; color: #64748b;"><strong>Device:</strong> {user_agent}</p>
              </div>

              <p style="font-size: 15px; color: #475569;">If this was you, you can safely ignore this email.</p>
              <p style="font-size: 15px; color: #dc2626; font-weight: 600;">If you do not recognize this activity, please change your password immediately and review your account security settings.</p>
            </div>
          </div>
        </body>
        </html>
        """
        msg.add_alternative(html_content, subtype='html')
        
        msg["Subject"] = "LifeOS - New Login Detected"
        msg["From"] = f"LifeOS Security <{settings.SMTP_EMAIL}>"
        msg["To"] = recipient_email
        
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(settings.SMTP_EMAIL, settings.SMTP_PASSWORD)
            server.send_message(msg)
            
        logger.info(f"Login alert email sent to {recipient_email}")
        return True
    except Exception as e:
        logger.error(f"Failed to send login alert to {recipient_email}: {str(e)}")
        return False

def send_sos_email(recipient_emails: List[str], user_name: str, location_url: Optional[str] = None) -> bool:
    """
    Sends an SOS emergency email to the provided list of contact emails.
    """
    settings = get_settings()
    
    if not settings.SMTP_EMAIL or not settings.SMTP_PASSWORD or settings.SMTP_PASSWORD == "PASTE_16_CHAR_APP_PASSWORD_HERE":
        logger.error("Email service is not configured! Check SMTP_EMAIL and SMTP_PASSWORD in .env")
        return False
        
    if not recipient_emails:
        return True
        
    try:
        msg = EmailMessage()
        
        # Fallback Plain Text
        text_content = (
            f"🚨 EMERGENCY ALERT 🚨\n\n"
            f"{user_name} has triggered an SOS emergency alert via LifeOS.\n\n"
            f"They may be in immediate danger or in need of urgent medical assistance.\n"
        )
        if location_url:
            text_content += f"\n📍 LIVE LOCATION:\n{location_url}\n\n"
        text_content += (
            f"Please attempt to contact them immediately.\n\n"
            f"This is an automated emergency message."
        )
        msg.set_content(text_content)
        
        # Aesthetic HTML Template
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <body style="margin: 0; padding: 0; background-color: #f8fafc; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;">
          <div style="max-width: 600px; margin: 40px auto; background-color: #ffffff; border-radius: 16px; overflow: hidden; box-shadow: 0 10px 25px rgba(220, 38, 38, 0.15); border: 2px solid #ef4444;">
            
            <!-- Header -->
            <div style="background: linear-gradient(135deg, #dc2626, #991b1b); padding: 32px 24px; text-align: center;">
              <div style="font-size: 48px; margin-bottom: 16px;">🚨</div>
              <h1 style="margin: 0; color: #ffffff; font-size: 28px; font-weight: 800; text-transform: uppercase; letter-spacing: 1px;">Emergency SOS Alert</h1>
            </div>

            <!-- Body -->
            <div style="padding: 40px 32px;">
              <p style="font-size: 18px; color: #1e293b; line-height: 1.6; margin-top: 0; font-weight: 600;">
                URGENT NOTIFICATION
              </p>
              
              <div style="background-color: #fef2f2; border-left: 4px solid #ef4444; padding: 20px; border-radius: 0 8px 8px 0; margin: 24px 0;">
                <p style="margin: 0; font-size: 18px; color: #7f1d1d;">
                  <strong style="font-size: 20px;">{user_name}</strong> has triggered an SOS emergency alert via LifeOS.
                </p>
              </div>

              <p style="font-size: 16px; color: #475569; line-height: 1.6; margin-bottom: 24px;">
                They may be in immediate danger or in need of urgent medical assistance. 
                Please attempt to contact them immediately.
              </p>

              {f'''
              <div style="background-color: #f8fafc; border: 1px solid #e2e8f0; padding: 16px; border-radius: 8px; margin-bottom: 24px; text-align: center;">
                <p style="margin: 0 0 12px 0; font-size: 15px; color: #334155; font-weight: 600;">📍 Live Location Shared</p>
                <a href="{location_url}" style="display: inline-block; background-color: #2563eb; color: #ffffff; text-decoration: none; padding: 10px 24px; border-radius: 6px; font-weight: 600; font-size: 15px;">View on Google Maps</a>
              </div>
              ''' if location_url else ''}

              <div style="text-align: center; margin-top: 32px;">
                <a href="{location_url if location_url else '#'}" style="display: inline-block; background-color: #ef4444; color: #ffffff; text-decoration: none; padding: 14px 32px; border-radius: 50px; font-weight: bold; font-size: 16px; text-transform: uppercase; letter-spacing: 0.5px;">Take Action Now</a>
              </div>
            </div>

            <!-- Footer -->
            <div style="background-color: #f1f5f9; padding: 24px; text-align: center; border-top: 1px solid #e2e8f0;">
              <p style="margin: 0; font-size: 13px; color: #64748b;">
                This is an automated emergency message sent securely via the LifeOS Emergency System.
              </p>
            </div>

          </div>
        </body>
        </html>
        """
        
        msg.add_alternative(html_content, subtype='html')
        
        msg["Subject"] = f"URGENT: Emergency SOS Alert from {user_name}"
        msg["From"] = f"LifeOS Emergency System <{settings.SMTP_EMAIL}>"
        msg["To"] = ", ".join(recipient_emails)
        
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(settings.SMTP_EMAIL, settings.SMTP_PASSWORD)
            server.send_message(msg)
            
        logger.info(f"SOS email successfully sent to {len(recipient_emails)} contacts")
        return True
        
    except Exception as e:
        logger.error(f"Failed to send SOS email: {str(e)}")
        return False

def send_sos_sms_twilio(phone_numbers: List[str], user_name: str, location_url: Optional[str] = None) -> tuple[bool, str]:
    """
    Sends an SOS SMS via Twilio. Returns (success, message).
    """
    from app.utils.twilio_support import configuration_error, create_client, normalize_phone, provider_error
    settings = get_settings()
    
    if error := configuration_error(settings):
        return False, error
    if settings.TWILIO_SMS_TEMPLATE_ONLY:
        return False, "SMS unavailable: this Twilio trial only permits preset templates. The SOS location SMS was not sent."
        
    if not phone_numbers:
        return False, "No phone numbers provided"
        
    try:
        # pyrefly: ignore [missing-import]
        client = create_client(settings)
        
        text = f"🚨SOS: {user_name} needs urgent help."
        if location_url:
            text += f" Loc: {location_url}"
            
        success_count = 0
        errors = []
        for number in phone_numbers:
            try:
                formatted_number = normalize_phone(number)
                
                message = client.messages.create(
                    body=text,
                    from_=settings.TWILIO_FROM_NUMBER,
                    to=formatted_number
                )
                logger.info(f"SOS SMS sent to {formatted_number} (SID: {message.sid})")
                success_count += 1
            except Exception as inner_e:
                err_msg = "SMS: " + provider_error(inner_e)
                logger.error(err_msg)
                errors.append(err_msg)
                if getattr(inner_e, "status", None) == 401 or getattr(inner_e, "code", None) == 20003:
                    break
                
        if success_count > 0:
            return True, f"SMS requests accepted: {success_count}." + (f" Failed: {len(errors)}." if errors else "")
        return False, " | ".join(errors)
    except Exception as e:
        return False, provider_error(e)

def send_sos_whatsapp_twilio(phone_numbers: List[str], user_name: str, location_url: Optional[str] = None) -> tuple[bool, str]:
    """
    Sends an SOS WhatsApp message via Twilio. Returns (success, message).
    """
    from app.utils.twilio_support import configuration_error, create_client, normalize_phone, provider_error
    settings = get_settings()
    
    if error := configuration_error(settings):
        return False, error
        
    if not phone_numbers:
        return False, "No phone numbers provided"
        
    whatsapp_from = settings.TWILIO_WHATSAPP_NUMBER or settings.TWILIO_FROM_NUMBER
    if not whatsapp_from.startswith("whatsapp:"):
        whatsapp_from = f"whatsapp:{whatsapp_from}"
        
    try:
        # pyrefly: ignore [missing-import]
        client = create_client(settings)
        
        # Format to match Twilio's pre-approved template: "Your {{1}} code is {{2}}"
        # This bypasses the WhatsApp 24-hour session requirement for testing.
        text = f"Your Emergency SOS code is {user_name}. Location: {location_url}"
            
        success_count = 0
        errors = []
        for number in phone_numbers:
            try:
                formatted_number = normalize_phone(number)
                whatsapp_to = f"whatsapp:{formatted_number}"
                
                message = client.messages.create(
                    body=text,
                    from_=whatsapp_from,
                    to=whatsapp_to
                )
                logger.info(f"SOS WhatsApp sent to {whatsapp_to} (SID: {message.sid})")
                success_count += 1
            except Exception as inner_e:
                err_msg = "WhatsApp: " + provider_error(inner_e)
                logger.error(err_msg)
                errors.append(err_msg)
                if getattr(inner_e, "status", None) == 401 or getattr(inner_e, "code", None) == 20003:
                    break
                
        if success_count > 0:
            return True, f"WhatsApp requests accepted: {success_count}." + (f" Failed: {len(errors)}." if errors else "")
        return False, " | ".join(errors)
    except Exception as e:
        return False, provider_error(e)

def send_sos_call_twilio(phone_numbers: List[str], user_name: str, location_url: Optional[str] = None, audio_url: Optional[str] = None) -> tuple[bool, str]:
    """
    Initiates an automated voice call via Twilio. Returns (success, message).
    """
    from app.utils.twilio_support import configuration_error, create_client, normalize_phone, provider_error, voice_instructions, recording_call_twiml, audio_url_problem, voice_url_problem, twiml_url
    settings = get_settings()
    
    if error := configuration_error(settings):
        return False, error
        
    if not phone_numbers:
        return False, "No phone numbers provided"
        
    try:
        # pyrefly: ignore [missing-import]
        client = create_client(settings)
        
        from xml.sax.saxutils import escape
        user_name = escape(user_name)
        audio_warning = ""
        if (settings.TWILIO_VOICE_USE_URL or audio_url):
            try:
                probe = '<Response><Hangup/></Response>'
                if problem := voice_url_problem(twiml_url(settings.PUBLIC_API_URL, probe), probe):
                    return False, problem
            except ValueError:
                return False, "Call not placed: PUBLIC_API_URL must be a reachable public server address."
        if audio_url and (problem := audio_url_problem(audio_url)):
            audio_url = None
            audio_warning = " Recording unavailable; used a spoken SOS instead. " + problem
        spoken = f"Emergency Alert. {user_name} has requested urgent help through LifeOS. Please contact them immediately."
            
        if audio_url:
            twiml_content = recording_call_twiml(settings.PUBLIC_API_URL, audio_url, spoken)
        else:
            twiml_content = f"<Response><Say voice='alice' language='en-US'>{spoken}</Say><Hangup/></Response>"
        
        success_count = 0
        errors = []
        for number in phone_numbers:
            try:
                formatted_number = normalize_phone(number)
                call = client.calls.create(
                    **voice_instructions(settings, twiml_content),
                    to=formatted_number,
                    from_=settings.TWILIO_FROM_NUMBER
                )
                logger.info(f"SOS Voice call initiated to {formatted_number} (SID: {call.sid})")
                success_count += 1
            except Exception as inner_e:
                err_msg = "Call: " + provider_error(inner_e)
                logger.error(err_msg)
                errors.append(err_msg)
                if getattr(inner_e, "status", None) == 401 or getattr(inner_e, "code", None) == 20003:
                    break
                
        if success_count > 0:
            return True, f"Call requests accepted: {success_count}." + (f" Failed: {len(errors)}." if errors else "") + audio_warning
        return False, " | ".join(errors)
    except Exception as e:
        return False, provider_error(e)

def send_organ_match_email(recipient_email: str, recipient_name: str, requester_name: str, organ: str, emergency_contact: str = None) -> bool:
    """
    Sends an email notifying the donor of an organ match request.
    """
    settings = get_settings()
    
    if not settings.SMTP_EMAIL or not settings.SMTP_PASSWORD or settings.SMTP_PASSWORD == "PASTE_16_CHAR_APP_PASSWORD_HERE":
        logger.error("Email service is not configured! Check SMTP_EMAIL and SMTP_PASSWORD in .env")
        return False
        
    try:
        msg = EmailMessage()
        msg.set_content(
            f"Hello {recipient_name},\n\n"
            f"A potential match has been found! {requester_name} has initiated a match process for: {organ}.\n\n"
            f"Please log in to your LifeOS account to review the request and contact your primary healthcare provider.\n"
            f"If you require immediate medical assistance, please contact the requester's emergency line at {emergency_contact or '108'}.\n\n"
            f"Thank you for being a registered organ donor."
        )
        msg["Subject"] = f"LifeOS - Organ Match Request Initiated: {organ}"
        msg["From"] = f"LifeOS Network <{settings.SMTP_EMAIL}>"
        msg["To"] = recipient_email
        
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(settings.SMTP_EMAIL, settings.SMTP_PASSWORD)
            server.send_message(msg)
            
        logger.info(f"Organ match email successfully sent to {recipient_email}")
        return True
        
    except Exception as e:
        logger.error(f"Failed to send organ match email to {recipient_email}: {str(e)}")
        return False

def send_mental_health_alert_email(recipient_emails: List[str], user_name: str) -> bool:
    """
    Sends an email to the emergency contact when a concerning mental health trend is detected.
    """
    settings = get_settings()
    
    if not settings.SMTP_EMAIL or not settings.SMTP_PASSWORD or settings.SMTP_PASSWORD == "PASTE_16_CHAR_APP_PASSWORD_HERE":
        return False
        
    if not recipient_emails:
        return True
        
    try:
        msg = EmailMessage()
        text_content = (
            f"Notification from LifeOS regarding {user_name}.\n\n"
            f"{user_name}'s recent journal entries indicate a concerning downward trend in their emotional well-being.\n"
            f"Please reach out to them and offer support.\n\n"
            f"This is an automated proactive wellness message."
        )
        msg.set_content(text_content)
        msg["Subject"] = f"LifeOS Wellness Alert: Please check on {user_name}"
        msg["From"] = f"LifeOS Wellness <{settings.SMTP_EMAIL}>"
        msg["To"] = ", ".join(recipient_emails)
        
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(settings.SMTP_EMAIL, settings.SMTP_PASSWORD)
            server.send_message(msg)
            
        logger.info(f"Mental health alert email successfully sent to {len(recipient_emails)} contacts")
        return True
    except Exception as e:
        logger.error(f"Failed to send mental health alert email: {str(e)}")
        return False

def send_mental_health_alert_sms(phone_numbers: List[str], user_name: str) -> bool:
    """
    Sends an SMS via Twilio to the emergency contact.
    """
    settings = get_settings()
    
    if not settings.TWILIO_ACCOUNT_SID or not settings.TWILIO_AUTH_TOKEN or not settings.TWILIO_FROM_NUMBER:
        return False
        
    if not phone_numbers:
        return True
        
    try:
        # pyrefly: ignore [missing-import]
        from twilio.rest import Client
        client = Client(settings.TWILIO_ACCOUNT_SID, settings.TWILIO_AUTH_TOKEN)
        
        text = f"LifeOS Wellness Alert: {user_name}'s recent mood tracking indicates they might be going through a tough time. Please reach out to check on them."
            
        success_count = 0
        for number in phone_numbers:
            try:
                formatted_number = number if number.startswith('+') else f"+{number}"
                message = client.messages.create(
                    body=text,
                    from_=settings.TWILIO_FROM_NUMBER,
                    to=formatted_number
                )
                logger.info(f"Mental health SMS sent to {formatted_number} (SID: {message.sid})")
                success_count += 1
            except Exception as inner_e:
                logger.error(f"Failed to send Mental health SMS to {number}: {str(inner_e)}")
                
        return success_count > 0
    except Exception as e:
        logger.error(f"Failed to connect to Twilio: {str(e)}")
        return False
